# Generated by Django 4.2.2 on 2023-07-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.FloatField()),
                ('parcelas', models.IntegerField(verbose_name='Numero de Parcelas')),
                ('data', models.DateField(verbose_name='Data de Vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_invest', models.CharField(max_length=100, verbose_name='Investimento')),
                ('valor', models.FloatField()),
                ('data', models.DateField(verbose_name='Data do investiento')),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoinvest', verbose_name='Tipo')),
            ],
        ),
    ]
